services:
  # 1. ฐานข้อมูล PostgreSQL
  db:
    image: pgvector/pgvector:pg16
    container_name: rag_postgres
    restart: unless-stopped
    # ดึงตัวแปรที่เกี่ยวกับ Database จากไฟล์ .env
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  # 2. Open WebUI
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open_webui
    restart: unless-stopped
    ports:
      - "${WEBUI_PORT}:8080"
    # ดึงตัวแปรที่เกี่ยวกับ WebUI จากไฟล์ .env
    env_file:
      - .env
    volumes:
      - webui_data:/app/backend/data
    depends_on:
      - db
    networks:
      - app_network
    environment:
      # native tools calling max times
      CHAT_RESPONSE_MAX_TOOL_CALL_ITERATIONS: "8"
      # web search
      ENABLE_WEB_SEARCH: "true"
      WEB_SEARCH_ENGINE: "ddgs"
      DDGS_BACKEND: "duckduckgo"
      WEB_SEARCH_RESULT_COUNT: "3"
      WEB_SEARCH_CONCURRENT_REQUESTS: "2"
      WEB_LOADER_CONCURRENT_REQUESTS: "2"
      WEB_LOADER_ENGINE: "safe_web"
      WEB_LOADER_TIMEOUT: "15"
      WEB_FETCH_MAX_CONTENT_LENGTH: "16000"
      ENABLE_WEB_SEARCH_CONFIRMATION: "true"
       
  api:
    build: ./backend 
    container_name: assistant_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_HOST=db
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - app_network

volumes:
  pgdata:
  webui_data:

networks:
  app_network: